### PR TITLE
Move use

### PR DESCRIPTION
**Pull request by jonathanstowe**
For some reason with some very recent changes to rakudo we get:

```
t/trait.t ...... ===SORRY!=== Error while compiling /home/jonathan/devel/perl6/modules/JSON-Unmarshal/t/trait.t
Can't use unknown trait 'is unmarshalled-by' in an attribute declaration.
at /home/jonathan/devel/perl6/modules/JSON-Unmarshal/t/trait.t:8
    expecting any of:
        rw
        readonly
        box_target
        leading_docs
        trailing_docs
```
It seems having the JSON::Name used in the same scope that the other traits are defined, hides those traits.  Very odd.

I also added a .gitignore as a .precomp directory comes free with every execution :)

### CODE REVIEW

**Comment by tadzik** [comment]
Is it a rakudobug we should report before fixing this on our side? :)

**Comment by jonathanstowe** [comment]
It's precomp fallout, I'm not entirely sure *why* it is doing it, I guess a quick rakudobug just to check wouldn't hurt ;-)

**Comment by jonathanstowe** [comment]
I RT'd this with https://rt.perl.org/Ticket/Display.html?id=126804 but I think that the change should probably go in anyway pending someone actually making a call on whether it is a bug or not.

**Comment by jonathanstowe** [comment]
Hi,
I'd actually forgotten that JSON::Unmarshal is depended on by META6 which in term is depended on by Test::META which in turn is being used by a bunch of other modules, which can't be installed right now (without using notests,)  so it would be really, really cool if you could merge this now, with a view to reverting it later if and when the above RT gets fixed.

**Comment by tadzik** [comment]
Yeah, sorry, totally forgot about this. Thanks for the patch and for reminding me!

**Comment by jonathanstowe** [comment]
:+1:

**Pull request merged**
