### PR TITLE
Handle thing like "key" : null and number in json that supposed to ma…

### PR DESCRIPTION
**Pull request by Skarsnik**
…p to Int but passed as string ("key" : "123"

### CODE REVIEW

**Comment by tadzik** [comment]
Can you add some tests for that? I don't really see the usecase from the description

**Comment by Skarsnik** [comment]
Oh right, that should be clearer now :)

**Comment by jonathanstowe** [comment]
I think this will be fixed by #23

**Comment by tadzik** [comment]
#23 seems to do a similar thing, but it seems like the tests from this one don't pass on it.
First one in `t/any.t`: `{ json => '{ "any-attr" : null }', value => Any, type => Any }`. We currently get Mu instead. I think I'd rather have Any in there, opinions? @jonathanstowe 

As for the second failing test, in `t/types.t`: I don't think "42" should unpack into an Int 42. The test now fails, and, imho, rightfully so. @Skarsnik?

**Comment by Skarsnik** [comment]
I think my issue was when playing around with Discord API, big int number (ID in Discord case see https://github.com/Skarsnik/perl6-discord/blob/master/lib/Discord/User.pm6#L4) were passed as string because JSON probably does not support then as int. But I wanted to have them typed as Int in my class.

**Comment by jonathanstowe** [comment]
I'm cool with Any, I think the Mu is probably a result of the way the multis pan out, JSON::Fast gives an Any there, I'll take a look later.  It's probably just a case of providing an Any:U target.

**Pull request closed without merging**
